name: Generate All Opportunities JSON

on:
  push:
    branches:
      - main  # Trigger on direct commits to main
    paths:
      - 'opportunities/*.json'  # Only trigger for JSON files in the opportunities folder

  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'opportunities/*.json'

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Generate all_opportunities.json
      run: node scripts/generate-all-opportunities.js

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add opportunities/all_opportunities.json
        git commit -m 'Auto-generate all_opportunities.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
