name: Interface Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours

jobs:
  track-interfaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run interface tracker
        working-directory: _luminara-homebase/scripts
        run: python3 interfaces_tracker_github.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: tracker-results
          path: |
            _luminara-homebase/state.json
            _luminara-homebase/changes.json
            _luminara-homebase/changes.sql
