name: Interface Tracker

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes

jobs:
  track-interfaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run interface tracker
        working-directory: _luminara-homebase/scripts
        run: python3 interfaces_tracker.py

      - name: Commit & Push tracker results
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          git stash || echo "ℹ️ Nothing to stash"
          git pull --rebase origin ${{ github.ref_name }}
          git stash pop || echo "ℹ️ Nothing to pop"

          git add -f _luminara-homebase/state.json _luminara-homebase/changes.json _luminara-homebase/changes.sql

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Update interface tracker results [skip ci]"
            git push
          fi
